### PR TITLE
Fix the build on GHC 7.4 and earlier

### PR DESCRIPTION
**Pull request by RyanGlScott**
Building `mockery` on GHC 7.4 errored with:

```
[1 of 3] Compiling Test.Mockery.Logging ( src/Test/Mockery/Logging.hs, dist/build/Test/Mockery/Logging.o )

src/Test/Mockery/Logging.hs:22:27:
    Not in scope: atomicModifyIORef'
    Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)
```

Luckily, `mockery` is already using `base-compat`, so fixing this is simple.

### CODE REVIEW

**Comment by sol** [comment]
Thanks for the patch!
